# Generated by Django 4.2.6 on 2023-10-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerecognition',
            old_name='emotion',
            new_name='dominant_emotion',
        ),
    ]
