# Generated by Django 4.2.6 on 2023-10-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_rename_emotion_imagerecognition_dominant_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='word_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
