# Generated by Django 4.2.6 on 2023-10-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_alter_videorecognition_word_per_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerecognition',
            name='name',
        ),
        migrations.AddField(
            model_name='imagerecognition',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
