# Generated by Django 4.2.6 on 2023-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_remove_imagerecognition_image_imagerecognition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerecognition',
            name='name',
        ),
        migrations.AddField(
            model_name='imagerecognition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
