# Generated by Django 4.2.6 on 2023-10-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0006_remove_imagerecognition_name_imagerecognition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecognition',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
