# Generated by Django 4.2.6 on 2023-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_imagerecognition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
