# Generated by Django 4.2.6 on 2023-10-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0008_videorecognition_video_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageRecognition',
        ),
        migrations.DeleteModel(
            name='VideoRecognition',
        ),
    ]
