# Generated by Django 4.2.6 on 2023-10-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('pdf_text', models.TextField()),
            ],
        ),
    ]
