# Generated by Django 4.2.6 on 2023-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0013_videorecognition_language_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecognition',
            name='image_analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
