# Generated by Django 4.2.6 on 2023-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0014_imagerecognition_image_analysis_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='energy_level_analysis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
