# Generated by Django 4.2.6 on 2023-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0015_videorecognition_energy_level_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='filler_words_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
