# Generated by Django 4.2.6 on 2023-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0016_videorecognition_filler_words_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='frequently_used_word',
            field=models.TextField(blank=True, null=True),
        ),
    ]
