# Generated by Django 4.2.6 on 2023-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0017_videorecognition_frequently_used_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='voice_emotion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
