# Generated by Django 4.2.6 on 2023-11-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0018_videorecognition_voice_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='confidence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videorecognition',
            name='eye_bling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videorecognition',
            name='hand_movement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
