# Generated by Django 4.2.6 on 2023-11-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0019_videorecognition_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='eye_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
