# Generated by Django 4.2.6 on 2023-11-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0020_videorecognition_eye_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='thanks_gesture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
