# Generated by Django 4.2.6 on 2023-11-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0021_videorecognition_thanks_gesture'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='greeting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
