# Generated by Django 4.2.6 on 2023-11-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0022_videorecognition_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='greeting_gesture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
