# Generated by Django 4.2.6 on 2023-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0023_videorecognition_greeting_gesture'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='voice_tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
