# Generated by Django 4.2.6 on 2023-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0024_videorecognition_voice_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='voice_pauses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
