# Generated by Django 4.2.6 on 2023-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0025_videorecognition_voice_pauses'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='appropriate_facial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
