# Generated by Django 4.2.6 on 2023-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0027_videorecognition_body_posture'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='voice_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
