# Generated by Django 4.2.6 on 2023-11-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0028_videorecognition_voice_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorecognition',
            name='voice_quality',
        ),
    ]
