# Generated by Django 4.2.6 on 2023-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0029_remove_videorecognition_voice_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='voice_modulation_analysis',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
