# Generated by Django 4.2.6 on 2023-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0030_alter_videorecognition_voice_modulation_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='language_analysis',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
