# Generated by Django 4.2.6 on 2023-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0031_alter_videorecognition_language_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='analysis_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
