# Generated by Django 4.2.6 on 2023-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0032_videorecognition_analysis_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='analysis_score',
            field=models.FloatField(default=75),
        ),
    ]
