# Generated by Django 4.2.6 on 2023-12-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0034_alter_videorecognition_analysis_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='filler_words_used',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorecognition',
            name='frequently_used_word',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
