# Generated by Django 4.2.6 on 2023-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0036_alter_videorecognition_voice_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='user',
            field=models.BigIntegerField(null=True),
        ),
    ]
