# Generated by Django 4.2.6 on 2023-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0037_videorecognition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='thumbs',
            field=models.FileField(blank=True, null=True, upload_to='thumbs/'),
        ),
    ]
