# Generated by Django 4.2.6 on 2023-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0038_videorecognition_thumbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorecognition',
            name='thumbs',
        ),
        migrations.AddField(
            model_name='videorecognition',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
