# Generated by Django 4.2.6 on 2023-12-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0039_remove_videorecognition_thumbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='body_language_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
