# Generated by Django 4.2.6 on 2023-12-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0040_videorecognition_body_language_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='facial_expression_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
