# Generated by Django 4.2.6 on 2023-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0042_rename_facial_expression_ratio_videorecognition_facial_expression_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='language_analysis_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorecognition',
            name='language_analysis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
