# Generated by Django 4.2.6 on 2023-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0043_videorecognition_language_analysis_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='voice_modulation_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
