# Generated by Django 5.0 on 2023-12-26 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0045_videorecognition_body_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
