# Generated by Django 5.0 on 2023-12-26 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0047_alter_videorecognition_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecognition',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 9, 31, 53, 776020, tzinfo=datetime.timezone.utc)),
        ),
    ]
