# Generated by Django 5.0 on 2023-12-26 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0048_alter_videorecognition_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecognition',
            name='facial_expression',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videorecognition',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
