# Generated by Django 5.0 on 2023-12-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0049_videorecognition_facial_expression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='frames/')),
            ],
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.videorecognition')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames', models.ManyToManyField(blank=True, to='machine_learning.frame')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.posture')),
            ],
        ),
    ]
