# Generated by Django 5.0 on 2023-12-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0050_frame_posture_detectedframes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedframes',
            old_name='video',
            new_name='posture',
        ),
    ]
