# Generated by Django 5.0 on 2023-12-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0051_rename_video_detectedframes_posture'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
