# Generated by Django 5.0 on 2024-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0052_frame_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='current_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videorecognition',
            name='video_durations',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
